### ISSUE TITLE
shootTime never reaches zero in multiplayer

### ISSUE THREAD

**Issue by concuror** [micdoodle8/Crossbow_Mod_2#16]
Hello.

I'd like to point out a bug, where in multiplayer crossbow only shoots once.
I have managed to find what causes it, but since I'm neither java dev, nor minecraft modder, it might be better that you fix this faster and in more correct fashion.

What I've found is that on client, method onTickInGame() fire correctly and thus variable shootTime reaches zero, whereas in multiplayer is isn't happening, so after first shot shootTime never gets down to zero.

**Comment by micdoodle8** [comment]
Thanks for reporting, this will be fixed in the next build. (0.2.14)
